name: Spin's Blog
title: Splog | A place for Spin to blog about anything.
description: A collection of blogs that Spin has written over time. 
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
  - spinfal
  - spin
  - coding
  - code
  - programming
  - software engineering
  - software
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: contact@spin.rip
# See: https://disqus.com/
disqus_username: spinfal
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id
